name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  contracts:
    name: Foundry build + test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install OpenZeppelin
        run: forge install OpenZeppelin/openzeppelin-contracts --no-commit --no-git || true

      - name: Show forge version
        run: forge --version

      - name: Build
        run: forge build --sizes

      - name: Test
        run: forge test -vv

  web:
    name: Next.js lint + build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile || bun install

      - name: Typecheck
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build
        env:
          NEXT_PUBLIC_CHAIN_ID: "5003"
          NEXT_PUBLIC_CHAIN_NAME: "Mantle Sepolia"
          NEXT_PUBLIC_RPC_URL: "https://rpc.sepolia.mantle.xyz"
          NEXT_PUBLIC_EXPLORER_URL: "https://explorer.sepolia.mantle.xyz"
